### ISSUE TITLE
CloudFront

### ISSUE THREAD

**Issue by braco** [svdgraaf/serverless-basic-authentication#2]
Would it make sense to reuse this plugin for CloudFront basic auth?

* http://kynatro.com/blog/2018/01/03/a-step-by-step-guide-to-creating-a-password-protected-s3-bucket/
* https://github.com/dumrauf/serverless_static_website_with_basic_auth
* https://hackernoon.com/serverless-password-protecting-a-static-website-in-an-aws-s3-bucket-bfaaa01b8666

**Comment by svdgraaf** [comment]
I think that's outside of the purpose of this plugin. Also, I frown a bit on the implementation, sure it's possible, but it seems a bit how you doing. Also, I don't think the cloudfront lambda layer is cached? Which potentially could become a very costly ordeal.

Api gateway authenticator calls can be cached for a specific amount of time, so you won't incur the lambda costs.

Anyone who wants to use this plugin as a base for such a project, go right ahead, but it's outside of the scope of this plugin.
