### ISSUE TITLE
Tried the npm plugin verbatim

### ISSUE THREAD

**Issue by jnguyen32** [svdgraaf/serverless-basic-authentication#3]
Getting this issue:

{"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=Basic xxx"}

When I attempt to:

curl -u key:value endpoint

Is there something missing from the documentation?

**Comment by svdgraaf** [comment]
I guess there is :D 

I have some time this week to spend on this, so I expect this to be fixed / documented :)

**Comment by svdgraaf** [comment]
@jnguyen32 I just tried this with a new api, and everything seems to work (aside from a missing dependency) out of the box.

Are you sure you are sending the credentials correctly? In your api there should be an authorizer configured:

![screenshot 2019-01-14 10 10 07](https://user-images.githubusercontent.com/19777/51103874-9ae21180-17e4-11e9-9de1-20f7f4da5092.png)

The api key source source should be set to `authorizer`:
![screenshot 2019-01-14 10 10 44](https://user-images.githubusercontent.com/19777/51103919-c1a04800-17e4-11e9-9f84-5c450d7d9ca3.png)

Your function should look a little like this:
![screenshot 2019-01-14 10 11 54](https://user-images.githubusercontent.com/19777/51103973-f3191380-17e4-11e9-9d58-5dfc5564528e.png)
![screenshot 2019-01-14 10 12 39](https://user-images.githubusercontent.com/19777/51103974-f3191380-17e4-11e9-8adb-3d81fbb4abea.png)

This should all be configured automatically out of the box when you install the plugin and set your function to something like this:

```
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: foo/bar
          method: get
          private: true
```

Let me know if this is the case, and I'll help you debug :)

**Comment by svdgraaf** [comment]
Closing this because of no response, if you're still having this issue, please let me know
